---
SONGS:
  - Picture to Burn
STYLES:
  - black and white street photograph
INSTRUCTIONS:         # Optional list of instructions
  - photo             # Reinforce you want a photo
  - no_text           # Reinforce you want no text

OPENAI:
  OPEN_AI_KEY: 
  BASE_URL: https://api.openai.com/v1/
